name: reditbot
channels:
  - defaults
dependencies:
  - anaconda_prompt=1.1.0=haa95532_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_0
  - python=3.10.18=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiohttp-retry==2.9.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==4.0.3
      - attrs==25.4.0
      - blinker==1.9.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dacite==1.9.2
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - filelock==3.20.0
      - filetype==1.2.0
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.35.3
      - idna==3.11
      - imagehash==4.3.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.11.0
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.9
      - langchain==0.3.27
      - langchain-community==0.3.31
      - langchain-core==0.3.79
      - langchain-openai==0.3.35
      - langchain-pinecone==0.2.12
      - langchain-text-splitters==0.3.11
      - langsmith==0.4.34
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.0
      - minify-html==0.18.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - multimethod==1.12
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - nltk==3.9.2
      - numba==0.62.1
      - numpy==2.2.6
      - openai==2.3.0
      - orjson==3.11.3
      - packaging==24.2
      - pandas==2.3.3
      - patsy==1.0.2
      - phik==0.12.5
      - pillow==11.3.0
      - pinecone==7.3.0
      - pinecone-client==6.0.0
      - pinecone-plugin-assistant==1.8.0
      - pinecone-plugin-interface==0.0.7
      - praw==7.8.1
      - prawcore==2.4.0
      - propcache==0.4.1
      - puremagic==1.30
      - pydantic==2.12.1
      - pydantic-core==2.41.3
      - pydantic-settings==2.11.0
      - pyparsing==3.2.5
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentence-transformers==5.1.1
      - simsimd==6.5.3
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.57.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - update-checker==0.18.0
      - urllib3==2.5.0
      - vadersentiment==3.3.2
      - visions==0.8.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - wordcloud==1.9.4
      - yarl==1.22.0
      - ydata-profiling==4.18.0
      - zstandard==0.25.0
prefix: C:\Users\jonis\anaconda3\envs\reditbot
